services:
  httplaceholder:
    image: dukeofharen/httplaceholder:2024.12.27.10
    environment:
      verbose: 'true'
      dev: true
      inputFile: '/etc/httplaceholder'
    ports:
      - "5001:5000"
    volumes:
      - ./scripts/dev/stubs:/etc/httplaceholder
  nuxt-demo:
    build:
      context: .
    ports:
      - "3001:3000"